### ISSUE TITLE
readme has wrong line break

### ISSUE THREAD

**Issue by ritsch** [iem-projects/pd-iem#3]
so it is hard to read on windows machines.

**Comment by umlaeute** [comment]
which one?

the README.txt that's included in the released zip-file should have the linebreaks corrected to CRLF, and according to my tests it does:

```
$ unzip pd-iem_v0.0.20150507.1447_w32.zip 
$ file pd-iem/README.txt 
pd-iem/README.txt: ASCII text, with CRLF line terminators
```

**Comment by ritsch** [comment]
Hmmm, the version stored at
http://puredata.info/downloads/pd-iem/releases/0.3alpha/pd-iem_v0.0.20150504.1702_w32.zip
has readme.md and has only CR.... 
 maye we should update

**Comment by umlaeute** [comment]
yes, always use the newest version :-)
